# Serve enviroment
FROM nginx:stable-alpine

# Copy build application
COPY dist /usr/share/nginx/html

# Copy config file
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]