import Head from "next/head";
import { Page, useGameStatus } from "ui";

export default function Home() {
  const { data: status } = useGameStatus();

  return (
    <Page>
      <Head>
        <title>Werewolf</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>{status ? "You are part of a game" : "No game started yet"}</h1>
      </main>
    </Page>
  );
}
