import Head from "next/head";
import { useGameStatus } from "ui";
import Layout from "../layout/default";
import { preloadTranslations } from "../lib/localization";

export const getStaticProps = preloadTranslations;

export default function Home() {
  const { data: status } = useGameStatus();

  return (
    <>
      <Head>
        <title>Werewolf</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1>{status ? "You are part of a game" : "No game started yet"}</h1>
      </Layout>
    </>
  );
}
