import Head from "next/head";
import { useGameStatus } from "ui";

export default function Home() {
  const { data: game, error, status } = useGameStatus();

  return (
    <>
      <Head>
        <title>Werewolf</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>Hello World</main>
      <pre>
        {status}: {error ? error.message : JSON.stringify(game)}
      </pre>
    </>
  );
}
