name: Release

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  GITHUB_REPO: ${{ github.repository }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - run: bun run build --filter=web...
        env:
          VITE_REPOSITORY: ${{ env.GITHUB_REPO }}
          VITE_SHA: ${{ github.sha }}
          VITE_VERSION: ${{ github.ref_name }}

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.GITHUB_REPO }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: apps/web
          file: apps/web/Dockerfile.prebuild
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
